import dgl
import torch
import torch.nn as nn
import torch.nn.functional as F
import itertools
import numpy as np
import scipy.sparse as sp


# 基本框架
# Load a DGL-provided dataset.
# Build a GNN model with DGL-provided neural network modules.
# Train and evaluate a GNN model for node classification on either CPU or GPU.

# 1. Create fake data(Build our graph)
# N = 100  # Number of nodes
# embed = nn.Embedding(N, 64)

# Realtime node:
# Nodes feature is generated by numpy


# 2. Build model

# 3. Train !

# 4. Evaluate !

